<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Menu_Masuk</name>
   <tag></tag>
   <elementGuidId>2d7ed04e-88c0-4517-8f3a-022461b17992</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[4]/header/div/div/div/div/div[2]/div[2]/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._1unphw40.tcmsgwfr > div._1unphw40.tcmsgwn.tcmsgw5b._10angag1 > div._1unphw40.tcmsgwn.tcmsgwhr.tcmsgw5b.tcmsgwgj > div._1unphw40.tcmsgw5b.tcmsgwh7.tcmsgwgf.tcmsgw6r.tcmsgwhn._1ko6ujc0 > a._1unphw40._1unphw4f._1unphw40.tcmsgw63.tcmsgwp.tcmsgw5f.tcmsgw5b.tcmsgwgj.tcmsgwgv.tcmsgwz.tcmsgwy.tcmsgw5.tcmsgwib.tcmsgw4.tcmsgwh._47d8pl0._47d8pl7._1dylamv0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=banner >> internal:role=link[name=&quot;Masuk&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c8650fec-9270-4bed-af2a-9efe38a23e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/id/oauth/login/?returnUrl=https%3A%2F%2Fid.jobstreet.com%2F</value>
      <webElementGuid>ba0675b0-e28e-496a-a851-4e580efcd1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>6ced321c-9156-42f2-8933-d1e6d5819c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1unphw40 _1unphw4f  _1unphw40 tcmsgw63 tcmsgwp tcmsgw5f tcmsgw5b tcmsgwgj tcmsgwgv tcmsgwz tcmsgwy tcmsgw5 tcmsgwib tcmsgw4 tcmsgwh _47d8pl0 _47d8pl7 _1dylamv0</value>
      <webElementGuid>36ae21a5-3586-41dc-b825-296258f2ee1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>43352162-9492-4846-8f40-dfebcd439a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>sign in</value>
      <webElementGuid>6bd68014-f9e9-4aee-bd50-c780c073ded5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>007dc36f-83cb-4725-8cb4-0a13e65f0fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>db16a932-470d-4719-a0b9-2d2dbc4b0a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;_13nud6w0 _1siu89c18 _1siu89c1b&quot;]/div[4]/header[@class=&quot;_1unphw40 _1unphw41&quot;]/div[@class=&quot;_1unphw40 tcmsgw8j tcmsgw7s tcmsgw9n tcmsgw8w tcmsgw5b tcmsgwhf tcmsgwgv tcmsgwp tcmsgw5g _1siu89c18 _1siu89c1b tcmsgw33 tcmsgw36&quot;]/div[@class=&quot;_1unphw40 tcmsgwbv tcmsgwaw tcmsgwar tcmsgw9s&quot;]/div[@class=&quot;_1unphw40 tcmsgwp tcmsgwv _1x5wtfb0&quot;]/div[@class=&quot;_1unphw40 tcmsgw5b tcmsgwhf tcmsgwh8 tcmsgwgr tcmsgwh4&quot;]/div[@class=&quot;_1unphw40 tcmsgw4v tcmsgw5c&quot;]/div[@class=&quot;_1unphw40 tcmsgwfr&quot;]/div[@class=&quot;_1unphw40 tcmsgwn tcmsgw5b _10angag1&quot;]/div[@class=&quot;_1unphw40 tcmsgwn tcmsgwhr tcmsgw5b tcmsgwgj&quot;]/div[@class=&quot;_1unphw40 tcmsgw5b tcmsgwh7 tcmsgwgf tcmsgw6r tcmsgwhn _1ko6ujc0&quot;]/a[@class=&quot;_1unphw40 _1unphw4f  _1unphw40 tcmsgw63 tcmsgwp tcmsgw5f tcmsgw5b tcmsgwgj tcmsgwgv tcmsgwz tcmsgwy tcmsgw5 tcmsgwib tcmsgw4 tcmsgwh _47d8pl0 _47d8pl7 _1dylamv0&quot;]</value>
      <webElementGuid>9a7822e6-defe-4ddf-95cd-7a0a88276cbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[4]/header/div/div/div/div/div[2]/div[2]/div/div/div/a</value>
      <webElementGuid>4b2faefa-974f-4bfe-84ee-20903454f535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bahasa'])[3]/following::a[1]</value>
      <webElementGuid>62cc289a-8b82-4fce-ab7d-5ba436129746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Untuk perusahaan'])[1]/following::a[1]</value>
      <webElementGuid>791d1d17-b53f-4f16-92a3-eca6634d32bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Untuk perusahaan'])[2]/preceding::a[1]</value>
      <webElementGuid>6d086e94-723b-45fc-91ac-145d09850cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/id/oauth/login/?returnUrl=https%3A%2F%2Fid.jobstreet.com%2F')])[2]</value>
      <webElementGuid>edbfeeb9-d7ac-483e-af31-2b4b82a48609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/a</value>
      <webElementGuid>6e92f4f8-c471-40ea-ab7c-75d52e0e41ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/id/oauth/login/?returnUrl=https%3A%2F%2Fid.jobstreet.com%2F' and @title = 'Masuk' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>9ac0f72d-f2d5-4d36-b9b1-757efe34703b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
