<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Masuk</name>
   <tag></tag>
   <elementGuidId>0a49c921-601a-463c-935a-f47b53cccd74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button._6khce80._6khce87._1wda6wv63._1wda6wvp._1wda6wv5f._1wda6wv4z._1wda6wvz._1wda6wvy._1wda6wv5._1wda6wvib._1wda6wv4._1wda6wvh._11vrhb10._11vrhb16.gu7kta19.gu7kta1b._1wda6wv17._1wda6wv18</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Masuk&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ea3f06d9-f8f9-4500-a353-6bee91677b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6khce80 _6khce87 _1wda6wv63 _1wda6wvp _1wda6wv5f _1wda6wv4z _1wda6wvz _1wda6wvy _1wda6wv5 _1wda6wvib _1wda6wv4 _1wda6wvh _11vrhb10 _11vrhb16 gu7kta19 gu7kta1b _1wda6wv17 _1wda6wv18</value>
      <webElementGuid>88d03cdb-62ed-4247-98b3-d19f8f565c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c29e2373-0041-4f78-9869-8e6cd93980e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>afce09c6-8599-4bb6-a08b-77372f7fe39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>b55f2872-9dc1-4416-8493-2f0e47c2a521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signin_seekanz&quot;)/div[@class=&quot;_6khce80 _1wda6wv5b _1wda6wvhf _1wda6wv6w _1wda6wv6x _1wda6wv6r&quot;]/div[@class=&quot;_6khce80 _1wda6wv5b _1wda6wvhf _1wda6wv7f&quot;]/button[@class=&quot;_6khce80 _6khce87 _1wda6wv63 _1wda6wvp _1wda6wv5f _1wda6wv4z _1wda6wvz _1wda6wvy _1wda6wv5 _1wda6wvib _1wda6wv4 _1wda6wvh _11vrhb10 _11vrhb16 gu7kta19 gu7kta1b _1wda6wv17 _1wda6wv18&quot;]</value>
      <webElementGuid>7174471b-c1b8-4ae7-8365-42ee73554140</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>29c5efc1-2bc4-4627-be19-0fba33ea4864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signin_seekanz']/div/div[3]/button</value>
      <webElementGuid>d198211b-eb4b-4e0d-938e-d5fe6ec069ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa kata sandi?'])[1]/following::button[2]</value>
      <webElementGuid>bc9ff3a9-1cf3-4ecf-83c6-8b1fc6e6e558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata sandi'])[1]/following::button[2]</value>
      <webElementGuid>b38a133b-f53e-4a5d-8a1e-3609b13614e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='atau'])[1]/preceding::button[1]</value>
      <webElementGuid>81ed7284-e231-4aa3-8d1e-76247d07d5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>b3133989-ebf6-4c55-b1e7-3b86f929cca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>ba28a5c0-31e4-40bf-bee0-4e2415266ee4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
