<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alamat email</name>
   <tag></tag>
   <elementGuidId>79db0515-829e-43d4-b75d-4334d6f0e884</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#emailAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Alamat email&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3e2ab2a-d9a5-4e4d-8092-35078718053d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6khce80 _6khce81 _6khce86 _6khce87 _6khce8c _1wda6wvp _1wda6wvb7 _1wda6wva3 _1wda6wv63 _1wda6wv5 _1p7otjd0 _1p7otjd1 gu7kta0 gu7kta1 gu7kta21 gu7ktai gu7kta26 gu7kta18  _1wda6wv33</value>
      <webElementGuid>55bf2f69-8b39-4ca5-b718-e6f7cfd4e502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>6c86f30d-92a3-44c4-8e47-34f4d13f6e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailAddress</value>
      <webElementGuid>0ba91300-3cb8-426b-b2a1-4b2ef47dfbda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emailAddress_seekanz</value>
      <webElementGuid>739d5ffa-90a6-4bff-8d39-2555a14c65e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>seekanz username</value>
      <webElementGuid>95cdd0e3-c702-4456-9522-dc21b3a9091e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>47dc3dfe-3986-4e91-bb1a-2541ea751e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7e6423f1-e07c-4386-83a8-fa4e90524b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailAddress&quot;)</value>
      <webElementGuid>50c4e422-ae01-4cfc-b36d-d4b451f095e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailAddress']</value>
      <webElementGuid>78604134-f3ba-4a1f-86b5-57f0b59c9d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signin_seekanz']/div/div/div[2]/div/input</value>
      <webElementGuid>ab62eede-6f41-4aac-b4b0-f1ecfba291f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6100cef7-a4fc-420e-b5fd-d82887345322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'emailAddress' and @name = 'emailAddress_seekanz']</value>
      <webElementGuid>5cae6d74-84e8-4518-9e2a-099f4926ad55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
